---
application:
  name: "product-api"
  project: "products-api"
  organization: "QoveryCommunity"
routers:
- name: "main-products-api"
  routes:
  - application_name: "products-api"
    paths:
    - "/*"
